name: Deploy Blazor WASM to GitHub Page
env:
  PUBLISH_DIR: bin/Release/net8.0/publish/wwwroot

# Controls when the action will run
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4

      - name: Publish application
        run: dotnet publish -c Release -v detailed

      - name: Use variables
        run: |
          echo "Working directory : $WORKING_DIR_VAR"
        env:
          WORKING_DIR_VAR: ${{ env.WORKING_DIRECTORY }}

      # base href url value should be changed so that resources like CSS and scripts can load properly. 
      #- name: Rewrite base href
      #  if: success()
      #  uses: SteveSandersonMS/ghaction-rewrite-base-href@v1.1.0
      #  with:
      #    html_path: ${{ env.PUBLISH_DIR }}/index.html
      #    base_href: /BlazorPrestige/

      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch ${{ env.PUBLISH_DIR }}/.nojekyll
      
      - name: Commit to GitHub pages Repo
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: ${{ env.PUBLISH_DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
